=== Saulgp-daw/DAM_DAD/TE9UD2/EjerciciosDTD/Parte1/Banco.dtd
<!ELEMENT cuentas ((copropietario |  cheques)*, ahorros)>
<!ELEMENT copropietario (#PCDATA)>
<!ELEMENT cheques (saldo, transaccion+, cargos)>
<!ELEMENT saldo (#PCDATA)>
<!ELEMENT transaccion (#PCDATA)>
<!ELEMENT cargos (#PCDATA)>
<!ELEMENT ahorros (saldo, intereses)>
<!ELEMENT intereses (#PCDATA)>

=== Saulgp-daw/DAM_DAD/TE9UD2/EjerciciosDTD/Parte1/ejercicio4_A.xml
<?xml version="1.0" encoding="ISO-8859-
1"?>
<!DOCTYPE cuentas SYSTEM "Banco.dtd">
<cuentas>
    <copropietario>John Doe</copropietario>
    <copropietario>Jack Smith</copropietario>
    <cheques>
        <saldo>170.00</saldo>
        <transaccion>-100.00</transaccion>
        <transaccion>-500.00</transaccion>
        <cargos>4.00</cargos>
    </cheques>
    <copropietario>John Doe</copropietario>
    <ahorros>
        <saldo>5000.00</saldo>
        <intereses>212.50</intereses>
    </ahorros>
</cuentas>
