=== Saulgp-daw/DAM_DAD/TE9UD2/EjerciciosDTD/Parte1/Productos.dtd
<!ELEMENT Productos (Items+, Impuesto, Entrega, Total)>
<!ELEMENT Items (Volumen?, Cantidad?, Descripcion, Precio, Total)>
<!ELEMENT Volumen (#PCDATA)>
<!ELEMENT Cantidad (#PCDATA)>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Precio (#PCDATA)>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Impuesto (#PCDATA)>
<!ELEMENT Entrega (#PCDATA)>

=== Saulgp-daw/DAM_DAD/TE9UD2/EjerciciosDTD/Parte1/ejercicio2_1.xml
<?xml version="1.0"?>
<!DOCTYPE Productos SYSTEM "Productos.dtd">
<Productos>
    <Items>
        <Cantidad>2</Cantidad>
        <Descripcion>Hamburguesas</Descripcion>
        <Precio>€2.25</Precio>
        <Total>€$4.5</Total>
    </Items>
    <Items>
        <Volumen>2 Litros</Volumen>
        <Descripcion>Coca Cola</Descripcion>
        <Precio>€1.25</Precio>
        <Total>€1.5</Total>
    </Items>
    <Impuesto>€0.25</Impuesto>
    <Entrega>A domicilio</Entrega>
    <Total>€6.25</Total>
</Productos>
