=== Saulgp-daw/DAM_DAD/Examen/Ejercicio3/ApartadoB/ListaFacturas.dtd
<!ELEMENT listafacturas (factura+)>
<!ELEMENT factura (emisor, pagador, importe)>
<!ATTLIST factura fecha CDATA #REQUIRED>
<!ELEMENT emisor ((dni | cif)?, nombre?, apellidos?, (razonsocial)?)>
<!ATTLIST emisor dni CDATA #IMPLIED>
<!ATTLIST emisor cif CDATA #IMPLIED>
<!ELEMENT pagador ((dni | cif)?, nombre, apellidos?, volumenventas)>
<!ATTLIST pagador dni CDATA #IMPLIED>
<!ATTLIST pagador cif CDATA #IMPLIED>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT razonsocial (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT volumenventas (#PCDATA)>

=== Saulgp-daw/DAM_DAD/Examen/Ejercicio3/ApartadoB/listafacturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listafacturas SYSTEM "ListaFacturas.dtd">
<listafacturas>
    <factura fecha="11-2-2015">
        <emisor dni="44111222A">
            <nombre>Antonio</nombre>
            <apellidos>Hernandez Dorta</apellidos>
        </emisor>
        <pagador cif="B368456">
            <nombre>ACME Inc</nombre>
            <volumenventas>2000</volumenventas>
        </pagador>
        <importe>2500</importe>
    </factura>
    <factura fecha="10-3-2015">
        <emisor cif="B368456">
            <razonsocial>ACME</razonsocial>
        </emisor>
        <pagador dni="41234999P">
            <nombre>Ana</nombre>
            <apellidos>Carrillo Solan</apellidos>
            <volumenventas>2000</volumenventas>
        </pagador>
        <importe>2500</importe>
    </factura>
</listafacturas>
